repos:
  # BLACK
  - hooks:
      - id: black
        language_version: python3
        args:
          - --line-length=80
    repo: https://github.com/psf/black
    rev: 22.3.0
  # DOCFORMATTER
  - hooks:
      - id: docformatter
        args:
          - -i
          - -r
          - --pre-summary-newline
          - --make-summary-multi-line
    repo: https://github.com/myint/docformatter
    rev: 'v1.4'
  # ISORT
  - hooks:
      - id: isort
        args:
          - --profile=black
          - --line-length=80
    repo: https://github.com/pycqa/isort
    rev: '5.10.1'