#!/usr/bin/env python

from argparse import ArgumentParser

from cars.scrapers.autotrader import init_parser as init_auotrader
from cars.scrapers.truecar import init_parser as init_truecar


def main() -> None:

    parser = ArgumentParser(prog="cars")
    sub = parser.add_subparsers()

    init_truecar(sub.add_parser("scrape-truecar"))
    init_auotrader(sub.add_parser("scrape-autotrader"))

    args = parser.parse_args()
    args.exe(args)


if __name__ == "__main__":
    main()
